Do not commit on master branch

diff --git a/.git_template/hooks/pre-commit b/.git_template/hooks/pre-commit
--- a/.git_template/hooks/pre-commit
+++ b/.git_template/hooks/pre-commit
@@ -15,3 +15,11 @@
 #if [ $? -ne 0 ]; then
 #    exit 1
 #fi
+
+
+# if the branch is master, then fail.
+branch="$(git symbolic-ref HEAD 2>/dev/null)" || "$(git describe --contains --all HEAD)"
+if [ "${branch##refs/heads/}" = "master" ]; then
+	echo "Do not commit on the master branch!"
+	exit 1
+fi
